DROP TABLE MEMBER;

CREATE TABLE MEMBER(
MEMBER_ID VARCHAR2(500) NOT NULL,
MEMBER_PW VARCHAR2(500) NOT NULL,
MEMBER_NAME VARCHAR2(1000),
MEMBER_EMAIL VARCHAR2(100),
MEMBER_PHONE VARCHAR2(100),
MEMBER_ENABLED VARCHAR2(2) NOT NULL,
MEMBER_ROLE VARCHAR2(20) NOT NULL,
CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_ID)
);



